CREATE TABLE tb_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40),
    username VARCHAR(40),
    cpf VARCHAR(11) UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(40) UNIQUE,
    birthdate DATE,
    monthly_income DOUBLE PRECISION,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE tb_expense (
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    price DOUBLE PRECISION NOT NULL,
    date DATE,
    necessary_expense BOOLEAN,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE tb_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(40) UNIQUE,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE tb_user_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255),
    user_user_id BIGINT,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_user_category_user FOREIGN KEY (user_user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_financial_planning (
    financial_planning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annual_goal DOUBLE PRECISION,
    monthly_goal DOUBLE PRECISION,
    user_id BIGINT,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_financial_planning_user FOREIGN KEY (user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    data_inclusao TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_report_user FOREIGN KEY (user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_category_expense (
    category_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    PRIMARY KEY (category_id, expense_id),
    CONSTRAINT fk_ce_category FOREIGN KEY (category_id) REFERENCES tb_category(category_id),
    CONSTRAINT fk_ce_expense FOREIGN KEY (expense_id) REFERENCES tb_expense(expense_id)
);

CREATE TABLE tb_user_category_expenses (
    user_category_category_id BIGINT NOT NULL,
    expenses_expense_id BIGINT NOT NULL UNIQUE, -- Unique para garantir OneToMany
    CONSTRAINT fk_uce_category FOREIGN KEY (user_category_category_id) REFERENCES tb_user_category(category_id),
    CONSTRAINT fk_uce_expense FOREIGN KEY (expenses_expense_id) REFERENCES tb_expense(expense_id)
);

CREATE TABLE tb_financial_planning_expenses (
    financial_planning_financial_planning_id BIGINT NOT NULL,
    expenses_expense_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_fpe_planning FOREIGN KEY (financial_planning_financial_planning_id) REFERENCES tb_financial_planning(financial_planning_id),
    CONSTRAINT fk_fpe_expense FOREIGN KEY (expenses_expense_id) REFERENCES tb_expense(expense_id)
);

